title: Linux Command Guide
description: Hướng dẫn sử dụng các lệnh Linux cơ bản
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Header tabs
header_pages:
  - index.md
  - manage_folder_navigation/README.md
  - manage_file/README.md
  - compression_and_extraction/README.md
  - manage_process_service/README.md
  - network_and_connect/README.md
  - permission_and_ownership/README.md
  - system_monitor/README.md

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - DEPLOY_GUIDE.md
